ZimaHrm.Web/Controllers/AttendenceController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ZimaHrm.Core.DataModel;
using ZimaHrm.Core.Infrastructure.Mapping;
using ZimaHrm.Core.ViewModel;
using ZimaHrm.Data.Repository.Interfaces;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ZimaHrm.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AttendenceController : Controller
    {
        private readonly IAttendenceRepository attendenceRepository;
        private readonly IDepartmentRepository departmentRepository;
        private readonly IEmployeeRepository employeeRepository;

        public AttendenceController(IAttendenceRepository attendenceRepository, 
            IDepartmentRepository departmentRepository, IEmployeeRepository employeeRepository)
        {
            this.attendenceRepository = attendenceRepository;
            this.departmentRepository = departmentRepository;
            this.employeeRepository = employeeRepository;
        }
        // get last 7 days attendence

        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.Departments = departmentRepository.GetAllDepartmentForDropDown();
            //ViewBag.Months = 
            return View();
        }

        [HttpPost]
        public ActionResult Index(AttendenceReportViewModel model)
        {
            var employees = employeeRepository.AllByDepartmentId(model.DepartmentId);
           
            int days = DateTime.DaysInMonth(DateTime.Now.Year, model.Month);
            DateTime firstdayofmonth = new DateTime(DateTime.Now.Year, model.Month, 1);
            DateTime lastdayofmonth = new DateTime(DateTime.Now.Year, model.Month, 1).AddMonths(1).AddDays(-1);

            var attendences = attendenceRepository.All().Where(x => x.AttendenceDate >= firstdayofmonth && x.AttendenceDate <= lastdayofmonth).ToList();
            AttendenceReportViewModel vm = new AttendenceReportViewModel();
            vm.DepartmentId = model.DepartmentId;
            vm.Month = model.Month;

            for (int i = 1; i <= days; i++)
            {
                string currentDate = new DateTime(DateTime.Now.Year, model.Month, i).ToShortDateString();
                vm.AllCurrentMonthDate.Add(currentDate);
            }

            foreach (var item in employees)
            {
                EmployeeStatustViewModel empStatusVm = new EmployeeStatustViewModel(days, model.Month);
                empStatusVm.EmployeeId = item.Id;
                empStatusVm.EmployeeName = item.Name;
                 var attendenceWithEmployee = attendences.Where(x => x.EmployeeId ==  item.Id).OrderBy(x=>x.AttendenceDate).ToList();
                foreach (var attEmp in attendenceWithEmployee)
                {
                    string attndDate = attEmp.AttendenceDate.ToShortDateString();
                    
                    if (vm.AllCurrentMonthDate.Contains(attndDate))
                    {
                        var statusR = empStatusVm.statustViewModel.FindIndex(x=>x.Date.ToShortDateString() == attndDate);
                        empStatusVm.statustViewModel.RemoveAt(statusR);

                        var status = new StatustViewModel();
                        status.Date = attEmp.AttendenceDate;
                        if (attEmp.Status == "Present")
                        {
                            status.Status = "Present";
                        }

                        if (attEmp.Status == "Absense")
                        {
                            status.Status = "Absense";
                        }
                        empStatusVm.statustViewModel.Insert(statusR,status);
                    }
                   
                }
                vm.StatusViewModel.Add(empStatusVm);
            }
            return View(vm);
        }

        // take attendence of the
        [HttpGet]
        public ActionResult TakeAttendence()
        {
            ViewBag.Departments = departmentRepository.GetAllDepartmentForDropDown();
            return View(new AttendenceViewModel());
        }
        [HttpPost]
        public ActionResult TakeAttendence(AttendenceViewModel model)
        {
            ViewBag.Departments = departmentRepository.GetAllDepartmentForDropDown();
            var attendences = attendenceRepository.All().Any(x => x.AttendenceDate == model.AttendenceDate);
            AttendenceViewModel vm = new AttendenceViewModel();
            vm.AttendenceDate = model.AttendenceDate;
            vm.DepartmentId = model.DepartmentId;
            if (attendences)
            {
                var attendecesList = attendenceRepository.All().Where(x => x.AttendenceDate == model.AttendenceDate).ToList();
                foreach (var item in attendecesList)
                {
                    vm.AttendenceListViewModel.Add(new AttendenceListViewModel { EmployeeId = item.EmployeeId,
                        AttendenceId = item.Id, Remark = item.Reason, Status = item.Status,
                        Name = employeeRepository.NameById(item.EmployeeId)});
                }
                return View(vm);
            }
            var employees = employeeRepository.AllByDepartmentId(model.DepartmentId);
            if (employees != null)
            {
                foreach (var item in employees)
                {
                    vm.AttendenceListViewModel.Add(new AttendenceListViewModel { EmployeeId = item.Id, Name = item.Name });
                }
                return View(vm);
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult SaveAttendence(AttendenceViewModel model)
        {
            if (model.AttendenceListViewModel.Count() > 0){
                foreach (var item in model.AttendenceListViewModel)
                {
                    if (item.AttendenceId == Guid.Empty)
                    {
                        //save 
                        attendenceRepository.Insert(new AttendenceModel { AttendenceDate= model.AttendenceDate,
                            EmployeeId = item.EmployeeId, Status = item.Status, Reason = item.Remark }.Map<Data.Entity.Attendence>());
                    }
                    else
                    {
                        // update 
                        var existingAttendence = attendenceRepository.Find(item.AttendenceId);
                        if (existingAttendence != null)
                        {
                            existingAttendence.Status = item.Status;
                            existingAttendence.Reason = item.Remark;
                            existingAttendence.EmployeeId = item.EmployeeId;
                            attendenceRepository.Update(existingAttendence, existingAttendence.Id);
                        }
                    }
                }
            }
            return RedirectToAction("TakeAttendence");
        }

        #region Private Methods 
        #endregion
    }
}

ZimaHrm.Web/Views/Attendence/Index.cshtml
@model ZimaHrm.Core.ViewModel.AttendenceReportViewModel

@{
    ViewData["Title"] = "Take Attendence";

}

<style>
    .margin-10 {
        margin-top: 6px;
    }

    .vertical-text {
        writing-mode: vertical-rl;
    }

    #customers {
        border-collapse: collapse;
        width: 100%;
    }

        #customers td, #customers th {
            border: 1px solid #ddd;
        }

        #customers tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        #customers tr:hover {
            background-color: #ddd;
        }

        #customers td {
            font-size: 13px;
        }

        #customers th {
            padding-top: 12px;
            padding-bottom: 12px;
            text-align: left;
            background-color: #4CAF50;
            color: white;
        }
</style>
<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h3 class="text-themecolor">Attendence Report </h3>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
            <li class="breadcrumb-item active">Attendence Report</li>
        </ol>
    </div>

    <div class="">
        <button class="right-side-toggle waves-effect waves-light btn-inverse btn btn-circle btn-sm pull-right m-l-10"><i class="ti-settings text-white"></i></button>
    </div>
</div>
<form method="post" asp-action="index" asp-controller="Attendence">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">

                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="DepartmentId"></label>
                                <select class="form-control" asp-for="DepartmentId">
                                    <option value="@Guid.Empty">All Employee</option>
                                </select>
                                <span asp-validation-for="DepartmentId" class="text-danger"></span>
                            </div>

                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="Month"></label>
                                @Html.DropDownListFor(x => x.Month, new List<SelectListItem>
                                {
                                    new SelectListItem() {Text = "January", Value="1"},
                                    new SelectListItem() {Text = "February", Value="2"},
                                    new SelectListItem() {Text = "March", Value="3"},
                                    new SelectListItem() {Text = "April", Value="4"},
                                    new SelectListItem() {Text = "May", Value="5"},
                                    new SelectListItem() {Text = "June", Value="6"},
                                    new SelectListItem() {Text = "July", Value="7"},
                                    new SelectListItem() {Text = "August", Value="8"},
                                    new SelectListItem() {Text = "September", Value="9"},
                                    new SelectListItem() {Text = "October ", Value="10"},
                                    new SelectListItem() {Text = "November", Value="11"},
                                    new SelectListItem() {Text = "December", Value="12"},
                                }, "Select Month", new { @class = "form-control" })
                                <span asp-validation-for="Month" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <br />
                            <input class="btn btn-primary margin-10" type="submit" value="Search Employee" />
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</form>

<div class="row">
    <div class="col-md-12">
        @if (Model != null)
        {
            <div class="card">
                <div class="card-body">
                    <table id="customers">
                        <thead>
                            <tr>
                                <td>Employee</td>

                                @foreach (var item in Model.AllCurrentMonthDate)
                                {
                                    <td>
                                        <span class="vertical-text">@item </span>
                                    </td>
                                }
                            </tr>
                        </thead>
                        @foreach (var emp in Model.StatusViewModel)
                        {

                            <tr>
                                <td> @emp.EmployeeName </td>
                                @foreach (var status in emp.statustViewModel)
                                {
                                    <td>
                                        @if (status.Status == "Present")
                                        {
                                            <span  class="fa  fa-check"> </span>

                                        }
                                        @if (status.Status == "Absense")
                                        {

                                            <span class="fa fa-times"></span>
                                        }
                                    </td>

                                }
                            </tr>
                        }
                    </table>
                </div>
            </div>
        }
    </div>
</div>

ZimaHrm.Web/Views/Attendence/TakeAttendence.cshtml
@model ZimaHrm.Core.ViewModel.AttendenceViewModel

@{
    ViewData["Title"] = "Take Attendence";
    int i = 0;
}
<style>
    .margin-10 {
        margin-top: 6px;
    }
</style>

<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h3 class="text-themecolor">Attendence </h3>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
            <li class="breadcrumb-item active">Attendence</li>
        </ol>
    </div>

    <div class="">
        <button class="right-side-toggle waves-effect waves-light btn-inverse btn btn-circle btn-sm pull-right m-l-10"><i class="ti-settings text-white"></i></button>
    </div>
</div>
<form method="post" asp-controller="Attendence" asp-action="TakeAttendence" >
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">

                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="DepartmentId"></label>
                                <select class="form-control" asp-for="DepartmentId">
                                    <option value="@Guid.Empty">All Employee</option>
                                </select>
                                @*<select class="form-control" asp-for="DepartmentId" asp-items="@(ViewBag.Departments)">
            <option value="@Guid.Empty">All Employee</option>
        </select>*@
                                <span asp-validation-for="DepartmentId" class="text-danger"></span>
                            </div>

                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="AttendenceDate">Attendence Date </label>
                                <input type="date" class="form-control" asp-for="AttendenceDate" />
                                <span asp-validation-for="AttendenceDate" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <br />
                            <input class="btn btn-primary margin-10" type="submit" value="Search Employee" />
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
 </form>





    @if (Model.AttendenceListViewModel != null)
    {
<form action="SaveAttendence" method="post">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Employeee</th>
                                <th>Status</th>
                                <th>Remark</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.AttendenceListViewModel)
                            {
                                <tr>
                                    <td>
                                        @item.Name
                                        <input type="hidden" name="AttendenceListViewModel[@i].AttendenceId" value="@item.AttendenceId" />
                                        <input type="hidden" name="AttendenceListViewModel[@i].EmployeeId" value="@item.EmployeeId" />
                                        <input type="hidden" asp-for="AttendenceDate" />
                                        <input type="hidden" asp-for="DepartmentId" />

                                    </td>
                                    <td>
                                        <select asp-for="@item.Status" name="AttendenceListViewModel[@i].Status" class="form-control">
                                            <option>Absense</option>
                                            <option>Present</option>
                                        </select>
                                    </td>
                                    <td>
                                        <input class="form-control" name="AttendenceListViewModel[@i].Remark" asp-for="@item.Remark" />
                                    </td>
                                </tr>
                                i++;
                            }

                        </tbody>
                    </table>
                </div>
                <div class="col-md-4">

                </div>
                <div class="col-md-offset-3 col-md-4">
                    <button type="submit" class="btn btn-success"> Save Changes</button>
                </div>

            </div>

        </div>
    </div>
</form>
}