ZimaHrm.Web/Controllers/PayRollController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using ZimaHrm.Core.DataModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Rotativa.AspNetCore;
using ZimaHrm.Data.Repository.Interfaces;
using ZimaHrm.Data.Repository.PaySlip;
using ZimaHrm.Data.Entity;
using ZimaHrm.Core.Infrastructure.Mapping;
using System.Threading.Tasks;
using ZimaHrm.Web.Services;

namespace ZimaHrm.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PayRollController : Controller
    {
        private readonly IAllowanceTypeRepository _allowanceTypeRepository;
        private readonly IAllowanceRepository _allowanceRepository;
        private readonly IDepartmentRepository _departmentRepository;
        private readonly IEmployeeRepository _employeeRepository;
        private readonly IAllowanceEmployee _allowanceEmployee;
        private readonly IPaySlipRepository _paySlipRepository;
        private readonly IEmployeePaySlipRepository _employeePaySlipRepository;
        private readonly IPaySlipAllowanceRepository _paySlipAllowanceRepository;
        private readonly IAuthenticatedUserService _currentUser;
        // GET: /<controller>/
        public PayRollController(IAllowanceTypeRepository allowanceTypeRepository,
                                 IAllowanceRepository allowanceRepository,
                                 IDepartmentRepository departmentRepository,
                                 IEmployeeRepository employeeRepository,
                                 IAllowanceEmployee allowanceEmployee,
                                 IPaySlipRepository paySlipRepository,
                                 IEmployeePaySlipRepository employeePaySlipRepository,
                                 IPaySlipAllowanceRepository paySlipAllowanceRepository,
                                 IAuthenticatedUserService currentUser)
        {
            this._allowanceTypeRepository = allowanceTypeRepository;
            this._allowanceRepository = allowanceRepository;
            this._departmentRepository = departmentRepository;
            this._employeeRepository = employeeRepository;
            this._allowanceEmployee = allowanceEmployee;
            this._paySlipRepository = paySlipRepository;
            this._employeePaySlipRepository = employeePaySlipRepository;
            this._paySlipAllowanceRepository = paySlipAllowanceRepository;
            _currentUser = currentUser;
        }

        #region Allowance Type List
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> AllowanceTypeList()
        {
            var allowanceTypes = await _allowanceTypeRepository.All()
                                                               .ToListAsync()
                                                               .ConfigureAwait(false);
            return View(allowanceTypes.Map<List<AllowanceTypeModel>>());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AllowanceTypeList(AllowanceTypeModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.Id != Guid.Empty)
                {
                    var updateDomain = model.Map<AllowanceType>();
                    _allowanceTypeRepository.Update(updateDomain, model.Id);
                    return RedirectToAction(nameof(AllowanceTypeList));
                }
                if (_allowanceTypeRepository.All().Any(x => x.AllowanceTypeName == model.AllowanceTypeName))
                {
                    ModelState.AddModelError("AllowanceTypeName", "Already Exists!");
                    return View(_allowanceTypeRepository.All().ToList().Map<List<AllowanceTypeModel>>());
                }

                var insertDomain = model.Map<AllowanceType>();
                _allowanceTypeRepository.Insert(insertDomain);
                return RedirectToAction(nameof(AllowanceTypeList));
            }
            return View(_allowanceTypeRepository.All().ToList().Map<List<AllowanceTypeModel>>());
        }

        public IActionResult DeleteAllowanceType(Guid id)
        {
            var allowanceType = _allowanceTypeRepository.Find(id);
            if (allowanceType != null)
            {
                _allowanceTypeRepository.Delete(allowanceType);
                return RedirectToAction(nameof(AllowanceTypeList));
            }
            return RedirectToAction(nameof(AllowanceTypeList));
        }
        #endregion

        #region Allowance
        [HttpGet]
        public IActionResult AllowanceList(Guid id)

        {
            ViewBag.Departments = _allowanceTypeRepository.GetAllForDropDown();
            ViewBag.AllowanceList = _allowanceRepository.All();
            if (id != Guid.Empty)
            {
                var allowance = _allowanceRepository.Find(id);
                return View(allowance.Map<AllowanceModel>());
            }
            return View(new AllowanceModel());
        }
        [HttpPost]
        public IActionResult AllowanceList(AllowanceModel model)
        {
            ViewBag.Departments = _allowanceTypeRepository.GetAllForDropDown();
            ViewBag.AllowanceList = _allowanceRepository.All();
            if (ModelState.IsValid)
            {
                if (model.Id != Guid.Empty)
                {
                    _allowanceRepository.Update(model.Map<Allowance>(), model.Id);
                    //success updated
                    return RedirectToActionPermanent(nameof(AllowanceTypeList), new { id = Guid.Empty });
                }
                if (_allowanceRepository.All().Any(x => x.AllowanceType == model.AllowanceType))
                {
                    ModelState.AddModelError("AllowanceType", "Already Added into allowance List");
                    ViewBag.Departments = _allowanceTypeRepository.GetAllForDropDown();
                    ViewBag.AllowanceList = _allowanceRepository.All();
                    return View(model);
                }
                _allowanceRepository.Insert(model.Map<Allowance>());
                return RedirectToAction(nameof(AllowanceTypeList));
            }
            return View(model);
        }
        public IActionResult DeleteAllowance(Guid id)
        {
            var allowance = _allowanceRepository.Find(id);
            if (allowance != null)
            {
                _allowanceRepository.Delete(allowance);
                //success
                return RedirectToAction(nameof(AllowanceTypeList));
            }
            //failed not found
            return RedirectToAction(nameof(AllowanceTypeList));
        }
        #endregion

        #region AllowanceEmployee
        [HttpGet]
        public IActionResult EmployeeWithAllowance()
        {
            ViewBag.Departments = _departmentRepository.GetAllDepartmentForDropDown();
            return View();
        }
        [HttpPost]
        public IActionResult SaveEmployeeAllowance(Guid empId, Guid[] ids)
        {

            if (empId != Guid.Empty && ids != null)
            {
                var allowancesForEmp = _allowanceEmployee.All().Where(x => x.EmployeeId == empId).ToList();
                foreach (var item in allowancesForEmp)
                {
                    _allowanceEmployee.Delete(item);
                }
                foreach (var id in ids)
                {
                    _allowanceEmployee.Insert(new AllowanceEmployeeModel { EmployeeId = empId, AllowanceId = id }.Map<AllowanceEmployee>());
                }
                //success
                return RedirectToAction(nameof(EmployeeWithAllowance));
            }
            return RedirectToAction(nameof(EmployeeWithAllowance));
        }

        [HttpGet]
        public JsonResult EmployeeByDeprt(Guid deptId)
        {
            return Json(_employeeRepository.AllByDepartmentId(deptId));
        }
        [HttpGet]
        public JsonResult AllowanceListByEmployee(Guid deptId, Guid empId)
        {
            var allowances = _allowanceRepository.All();
            var employeeWithAllowances = _allowanceEmployee.All()
                                                           .AsSplitQuery()
                                                           .Include(x => x.Allowance)
                                                           .Where(x => x.EmployeeId == empId);
            foreach (var allowance in allowances)
            {
                foreach (var emp in employeeWithAllowances)
                {
                    if (emp.Allowance == allowance)
                        allowance.isCheck = true;
                }
            }
            return Json(allowances);
        }

        #endregion

        #region PaySlip


        [HttpGet]
        public async Task<IActionResult> PaySlipList()
        {
            var paySlips = await _paySlipRepository.All().Select(s => new PaySlipModel
            {
                CreatedBy = s.CreatedBy,
                CreatedUtc = s.CreatedUtc,
                DepartmentId = s.DepartmentId,
                Description = s.Description,
                Id = s.Id,
                IsDelete = s.IsDelete,
                LastModifiedBy = s.LastModifiedBy,
                LastModifiedUtc = s.LastModifiedUtc,
                Month = s.Month,
                PaymentDate = s.PaymentDate,
                Title = s.Title,
                DepartmentName="All"
            })
                                                   .ToListAsync()
                                                   .ConfigureAwait(false);

            var departments = await _departmentRepository.All()
                                                       .ToDictionaryAsync(s => s.Id, s => s.Name)
                                                       .ConfigureAwait(false);

ZimaHrm.Web/Views/PayRoll/AllowanceList.cshtml
@model ZimaHrm.Core.DataModel.AllowanceModel
@{
    ViewData["Title"] = "Allowance/Deduction List";
    int i = 1;
}


<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h3 class="text-themecolor">Allowance List</h3>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="AllowanceList" asp-controller="PayRoll">Home</a></li>
            <li class="breadcrumb-item active">Allowance/Deduction List </li>
        </ol>
    </div>
</div>


<div class="row">
    @if (ViewBag.AllowanceList != null)
    {
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    @*<h4 class="card-title">Bordered Table</h4>
                        <h6 class="card-subtitle">Add<code>.table-bordered</code>for borders on all sides of the table and cells.</h6>*@
                    <div class="">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>A/D type</th>
                                    <th>Value</th>
                                    <th class="text-nowrap">Action</th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach (var item in ViewBag.AllowanceList)
                                {
                                    <tr>
                                        <td>@i</td>
                                        <td>
                                            @if (item.Type == "Allowance")
                                            {
                                                <span class="label label-table label-success" title="@item.Type">@item.AllowanceType</span>

                                            }
                                            @if (item.Type == "Deduction")
                                            {
                                                <span class="label label-table label-danger" title="@item.Type">@item.AllowanceType</span>

                                            }

                                        </td>
                                        <td>
                                            <span>
                                                @if (item.IsValue)
                                                {
                                                    <span> @item.Value TK</span>
                                                }
                                            </span>
                                            <span>
                                                @if (!item.IsValue)
                                                {
                                                    <span> @item.Value %</span>
                                                }
                                            </span>
                                        </td>

                                        <td class="text-nowrap">
                                            <a data-toggle="tooltip" asp-action="AllowanceList" asp-route-id="@item.Id" data-val-id="@item.Id" data-original-title="Edit" class="btnEdit"> <i class="fa fa-pencil text-inverse m-r-10"></i> </a>
                                            <a data-toggle="tooltip" data-original-title="Delete" asp-controller="PayRoll" asp-action="DeleteAllowance" asp-route-id="@item.Id" onclick="return confirm('are you sure want to delete?')"> <i class="fa fa-close text-danger"></i> </a>
                                        </td>
                                    </tr>
                                    i++;
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    }

    <div class="col-md-6">
        <div class="card">
            <div class="card-body">
                <form asp-controller="PayRoll" asp-action="AllowanceList" method="post">
                    <input type="hidden" value="@Model.Id" />

                    <div class="form-group">
                        <label> Type </label>
                        <select asp-for="Type" class="form-control">
                            <option value="">Select Type</option>
                            <option value="Allowance">Allowance</option>
                            <option value="Deduction">Deduction</option>
                        </select>
                        <span asp-validation-for="Type" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="AllowanceType"></label>
                        <select asp-for="AllowanceType" class="form-control" asp-items="@(ViewBag.Departments)">
                            <option value="">Select</option>
                        </select>
                        <span asp-validation-for="AllowanceType" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label> Value/Percent </label>
                        <select asp-for="IsValue" class="form-control">
                            <option value="true">Value</option>
                            <option value="false">Percent</option>
                        </select>
                        <span asp-validation-for="IsValue" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Value"></label>
                        <input type="text" asp-for="Value" class="form-control" id="Value" placeholder="Enter Value">
                        <span asp-validation-for="Value" class="text-danger"></span>
                    </div>


                    <button type="submit" id="btnSave" class="btn btn-sm btn-success waves-effect waves-light "><i class="fa fa-plus"></i> Add</button>

                </form>
            </div>
        </div>
    </div>
</div>

ZimaHrm.Web/Views/PayRoll/AllowanceTypeList.cshtml
@model IEnumerable<ZimaHrm.Core.DataModel.AllowanceTypeModel>
@{
    ViewData["Title"] = "Allowance/Deduction Type List";
    int i = 1;
}


<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h3 class="text-themecolor">Allowance/Deduction Type List</h3>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="AllowanceTypeList" asp-controller="PayRoll">Home</a></li>
            <li class="breadcrumb-item active">Allowance/Deduction Type List </li>
        </ol>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-body">
                @*<h4 class="card-title">Bordered Table</h4>
                    <h6 class="card-subtitle">Add<code>.table-bordered</code>for borders on all sides of the table and cells.</h6>*@
                <div class="">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Allowance/Deduction Type</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@i</td>
                                    <td>
                                        <p>@item.AllowanceTypeName</p>
                                    </td>

                                    <td class="text-nowrap">
                                        <a data-toggle="tooltip" data-val-id="@item.Id" data-original-title="Edit" class="btnEdit"> <i class="fa fa-pencil text-inverse m-r-10"></i> </a>
                                        <a data-toggle="tooltip" data-original-title="Delete" asp-controller="PayRoll" asp-action="DeleteAllowanceType" asp-route-id="@item.Id" onclick="return confirm('are you sure want to delete?')"> <i class="fa fa-close text-danger"></i> </a>
                                    </td>
                                </tr>
                                i++;
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card">
            <div class="card-body">
                <form asp-controller="PayRoll" asp-action="AllowanceTypeList" method="post">
                    <div class="form-group">
                        <label for="Name">Allowance/Deduction Type</label>
                        <input type="hidden" name="Id" value="@Guid.Empty" id="inputId" />
                        <input type="text" name="AllowanceTypeName" class="form-control" id="Name" placeholder="Enter Allowance/Deduction Type Name">
                        @Html.ValidationMessage("AllowanceTypeName", "", new { @class = "text-danger" })
                    </div>
                    <button type="submit" id="btnSave" class="btn btn-sm btn-success waves-effect waves-light "><i class="fa fa-plus"></i> Add</button>
                    <button type="button" id="btnCancel" class="btn btn-sm btn-danger waves-effect waves-light "><i class="fa fa-remove"></i> Cancel</button>

                </form>
            </div>
        </div>
    </div>
</div>


@section scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $(".btnEdit").click(function () {
                var id = $(this).attr("data-val-id");
                var name = $.trim($(this).closest('tr').children('td:eq(1)').text());
                if (name !== "" && id !== null) {
                    $("#Name").val(name);
                    $("#inputId").val(id);
                    $("#btnSave").html('<i class="fa fa-plus"></i> Update');
                }

            });

            $("#btnCancel").click(function () {
                $("#btnSave").html('<i class="fa fa-plus"></i> Add');
                $("#inputId").val('00000000-0000-0000-0000-000000000000');
                $("#Name").val("");
            });
        });
    </script>
}

ZimaHrm.Web/Views/PayRoll/EmpPaySlipDetails.cshtml
@model ZimaHrm.Core.DataModel.EmployeePaySlipModel
@{
    ViewData["Title"] = "Employee PaySlip List";
}


<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h3 class="text-themecolor">Allowance List</h3>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="AllowanceList" asp-controller="PayRoll">Home</a></li>
            <li class="breadcrumb-item active">Allowance/Deduction List </li>
        </ol>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="row">

                    <div class="col-md-12">
                        <a class="btn btn-primary btn-sm" href="@Url.Action("PrintPaySlip", new { id = Model.Id})"> <i class="fa fa-print"></i>  </a>
                        <br /><br />
                    </div>
                    

                    <div class="col-md-12">
                        <address class="pull-left">
                            <h4 class="font-bold">@Model.Employee.Name </h4>
                            <p class="m-l-30">
                                @Model.Employee.Email
                                <br />@Model.Employee.Mobile
                                <br /> @Model.Employee.PresentAddress
                            </p>
                        </address>
                        <address class="pull-right">
                            <p class="m-l-30">
                                Payment Month :  @Model.PaySlip.Month
                                <br />Payment Date :  @Model.PaySlip.PaymentDate.ToShortDateString()
                            </p>
                        </address>

                        @*<h4 class="card-title">Customer</h4>
        <span>@Model.Employee.Name </span> <br />
        <span>@Model.Employee.Email </span><br />
        <span>@Model.Employee.Mobile </span><br />
        <span>@Model.Employee.PresentAddress </span>*@
                    </div>

                    <div class="col-md-6">
                        <h4 class="card-title">Allowances</h4>
                        <table class="table color-table info-table table-bordered">
                            <thead>
                                <tr>
                                    <th>
                                        No
                                    </th>
                                    <th>
                                        Name
                                    </th>
                                    <th>Value</th>
                                    <th>Amount</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.PaySlipAllowances)
                                {
                                    if (item.AllowanceType == "Allowance")
                                    {

                                        <tr>
                                            <td> 1</td>
                                            <td> @item.AllowanceName </td>
                                            <td> @item.Value <span> @if (!item.IsValue)
{<span> %</span>}</span></td>
                                            <td> @item.Amount </td>

                                        </tr>

                                    }
                                }

                            </tbody>
                            <tfoot>
                                <tr>

                                    <td colspan="3">Total Allowance </td>
                                    <td> @Model.AllowanceTotal</td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                    <div class="col-md-6">
                        <h4 class="card-title">Deductions</h4>
                        <table class="table color-table danger-table table-bordered">
                            <thead>
                                <tr>
                                    <th>
                                        No
                                    </th>
                                    <th>
                                        Name
                                    </th>
                                    <th>Value</th>
                                    <th>Amount</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.PaySlipAllowances)
                                {
                                    if (item.AllowanceType == "Deduction")
                                    {

                                        <tr>
                                            <td> 1</td>
                                            <td> @item.AllowanceName </td>
                                            <td> @item.Value <span> @if (!item.IsValue)
{<span> %</span>}</span></td>
                                            <td> @item.Amount </td>

                                        </tr>
                                    }
                                }

                            </tbody>
                            <tfoot>
                                <tr>

                                    <td colspan="3">Total Deduction </td>
                                    <td> @Model.DeductionTotal</td>
                                </tr>
                            </tfoot>
                        </table>

                    </div>

                    

                    <div class="col-md-12">
                        <hr />
                        <table class="table table-bordered">
                            <tr>
                                <th><strong class="pull-right"> Basic Salarry</strong>  </th>
                                <th><strong class="pull-right"> Total Allowance</strong> </th>
                                <th><strong class="pull-right"> Total Deduction</strong></th>
                            </tr>
                            <tr>
                                <td><span class="pull-right">@Model.Employee.BasicSalary </span> </td>
                                <td> <span class="pull-right">@Model.AllowanceTotal </span> </td>
                                <td><span class="pull-right"> @Model.DeductionTotal</span> </td>
                            </tr>
                            <tr>
                                <td colspan="2"> <span class="pull-right"> <strong>Net Salary </strong> </span>  </td>
                                <td><span class="pull-right"> <strong> @Model.NetSalary </strong></span> </td>
                            </tr>
                        </table>
                    </div>

                </div>

            </div>
        </div>
    </div>
</div>

ZimaHrm.Web/Views/PayRoll/Index.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>title</h2>

ZimaHrm.Web/Views/PayRoll/PaySlipDetails.cshtml
@model IEnumerable<ZimaHrm.Core.DataModel.EmployeePaySlipModel>
@{
    ViewData["Title"] = "Employee PaySlip List";
    int i = 1;
}


<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h3 class="text-themecolor">Employee PaySlip List</h3>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Dashboard">Home</a></li>
            <li class="breadcrumb-item active">Employee PaySlip List </li>
        </ol>
    </div>
    <div class="col-md-7 align-self-center text-right d-none d-md-block">
        <a asp-action="CreatePaySlip" class="btn btn-info"><i class="fa fa-plus-circle"></i>New PaySlip</a>
    </div>

</div>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                @*<h4 class="card-title">Bordered Table</h4>
                    <h6 class="card-subtitle">Add<code>.table-bordered</code>for borders on all sides of the table and cells.</h6>*@
                <div class="">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Employee </th>
                                <th>Basic Salary </th>
                                <th>Total Allowance</th>
                                <th>Total Deduction</th>
                                <th>Net Salary</th>

                                <th class="text-nowrap">Action</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in Model)
                            {
                            <tr>
                                <td>@i</td>
                                <td>@item.Employee.Name</td>
                                <td>@item.BasicSalary</td>
                                <td>@item.AllowanceTotal</td>
                                <td>@item.DeductionTotal</td>
                                <td>@item.NetSalary</td>
                               
                                <td class="text-nowrap">
                                    <a data-toggle="tooltip" asp-controller="PayRoll" asp-action="EmpPaySlipDetails" asp-route-id="@item.Id" data-original-title="details" class="btnEdit"> <i class="fa fa-eye text-inverse m-r-10"></i> </a>
                                    <a data-toggle="tooltip" asp-controller="PayRoll" asp-action="DeleteDesignation" asp-route-id="@item.Id" data-original-title="Delete" onclick="return confirm('are you sure want to delete?')"> <i class="fa fa-close text-danger"></i> </a>
                                </td>
                            </tr>
                                i++;
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>


@section scripts {
    <script type="text/javascript">

    </script>
}